# Generated by Django 5.0.7 on 2024-07-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_votes_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Politics'), ('S', 'Sports'), ('G', 'Games'), ('M', 'Music'), ('F', 'Fashion'), ('D', 'Development & Programming'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
