# Generated by Django 5.0.7 on 2024-10-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='vote_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
